migration_mode = "skip"
pkgs_path = "/tmp"
create_workspace_permissions = "$SI_WORKSPACE_PERMISSIONS"
create_workspace_allowlist = [ "$SI_WORKSPACE_ALLOW_LIST" ]

concurrency_limit = $SI_PINGA_CONCURRENCY_LIMIT
data_warehouse_stream_name = "$SI_FORKLIFT_DATA_WAREHOUSE_STREAM_NAME"

[crypto]
encryption_key_base64 = "$SI_ENCRYPTION_KEY_BASE64"
decryption_key_base64 = "$SI_DECRYPTION_KEY_BASE64"

[cyclone]
connect_timeout = 100
pool_size = $SI_VERITECH_POOL_SIZE
runtime_strategy = "LocalFirecracker"

[jwt_signing_public_key]
key_base64 = "$SI_JWT_KEY_BASE64"

[nats]
creds = """
$SI_NATS_CREDS
"""
url = "$SI_NATS_URL"

[openai]
api_key = "$SI_OPENAI_API_KEY"
api_base = "$SI_OPENAI_API_BASE"
api_version = "$SI_OPENAI_API_VERSION"
org_id = "$SI_OPENAI_ORG_ID"

[asset_sprayer]
prompts_dir = "$SI_asset_sprayer_prompts_dir"

[pg]
user = "si"
password = "$SI_PG_PASSWORD"
dbname = "$SI_PG_DB"
application_name = "$SI_SERVICE"
hostname = "$SI_PG_PROXY_HOST"
port = 5432
pool_max_size = $SI_PG_POOL_SIZE

[service]
port = 5156

[symmetric_crypto_service]
active_key_base64 = "$SI_ACTIVE_KEY_BASE64"

[layer_db_config.pg_pool_config]
user = "si"
password = "$SI_PG_PASSWORD"
dbname = "$SI_LAYER_CACHE_DBNAME"
application_name = "$SI_SERVICE"
hostname = "$SI_PG_PROXY_HOST"
port = 5432
pool_max_size = $SI_PG_POOL_SIZE

[layer_db_config.nats_config]
creds = """
$SI_NATS_CREDS
"""
url = "$SI_NATS_URL"

[layer_db_config.memory_cache_config]
seconds_to_idle = "$SI_CACHE_EVICTION_SECONDS_TO_IDLE"

[layer_db_config.disk_cache_config]
path = "$SI_LAYER_CACHE_DISK_PATH"
cleanup_mode = "$SI_LAYER_CACHE_CLEANUP_MODE"
